id: PB0DC5D35
initial_creation_type: input
source_metadata:
  Title: Amoghapāśakalparāja Part VI
  Editor: SasakiItoTakumi
  Publisher: '-'
  Place of Publication: '-'
  Year: '2010'
  Amoghapāśakalparāja Part VI:
    Text Version: Romanized
    Input Personnel: Miroj Shakya
    Input Date: '2018'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:12:01.425225'
last_modified_at: '2022-03-08T17:12:01.425237'
